/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpClient;

import org.junit.Test;

public class ClientTest {
    @Test public void testSomeLibraryMethod() {

    }
}
