/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpClient;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.Scanner;

public class Client {
	public static void main(String[] args) throws Exception {
		System.out.println("start client >>>");

		String host = "localhost";
		int port = 80;

		Socket socket = new Socket(host, port);
		BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
		BufferedReader reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));

		Scanner scanner = new Scanner(System.in);
		System.out.println("リクエストを入力し、終わったら^Dで入力終了。");
		while (scanner.hasNext()) {

			String str = scanner.nextLine();
			writer.write(str + "\n");
		}
		writer.write("\n");

//		Scanner scan = new Scanner(System.in);
//		System.out.println("bodyを入力し、終わったら^Dで入力終了。");
//		while (scan.hasNext()) {
//			String str = scan.nextLine();
//			writer.write(str + "\n");
//		}
//		scan.close();

		System.out.println("<<< Request");
		scanner.close();


		writer.flush();

		String line = reader.readLine();
		System.out.println("Response >>>");
		while (line != null) {
			System.out.println(line);
			line = reader.readLine();
		}

		writer.close();
		reader.close();
		socket.close();
		System.out.println("<<< Response");
	}
}
